### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0151'

### ISSUE THREAD

**Issue by torzsok** [forscher21/mopidy-cd#10]
I managed to install to a 2010 mac mini with macos High Sierra, and it reads the disc info well. When I try to play a song, it does not start, and these are the messages I could collect from the terminal:

WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
WARNING  Track is not playable: cd:/9
Traceback (most recent call last):
  File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/internal/log.py", line 175, in emit
    message = self.format(record)
  File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/internal/log.py", line 183, in format
    message = logging.StreamHandler.format(self, record)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Logged from file actor.py, line 355
Traceback (most recent call last):
  File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/internal/log.py", line 176, in emit
    self.stream.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0151' in position 68: ordinal not in range(128)
Logged from file actor.py, line 314

Thanks in advance for any help.

**Comment by forscher21** [comment]
Seems some problem with the logging. Can you try to comment out the line https://github.com/forscher21/mopidy-cd/blob/5d36f744f419c601b1a991c51b5e80609edcc1c3/mopidy_cd/backend.py#L40 ?

**Comment by torzsok** [comment]
Thanks for the answer, it still does not play, though. Now it also ejects the disc for some reason.

**Comment by torzsok** [comment]
I got one more error message that showed up before. 
It was a completely fresh macOS install and until I started iTunes once to play a cd and i clicked OK on some permission thing, this line came right after the UniCode stuff:
ERROR    GStreamer error: gst-core-error-quark: No URI handler implemented for: „cdda”. (12)

I got rid of iTunes this evening completely, and now the same error message is back. I don't know if this is any helpful.

**Comment by torzsok** [comment]
Sorry, closed by accident.

**Comment by forscher21** [comment]
I don't have a macOS machine, so unfortunately I can't test it there. Could it be related to some missing gstreamer plugin? I am just guessing...

**Comment by torzsok** [comment]
Any suggestions on how to get more info and get closer to fixing it? What would you do if you had one?
